# Generated by Django 2.2.3 on 2019-12-13 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('tel', models.CharField(max_length=24, verbose_name='numero de télephone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_table', models.CharField(max_length=16, verbose_name='numero de table')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('somme', models.IntegerField(verbose_name='à payer')),
                ('payee', models.IntegerField(default=0, verbose_name='déjà payée')),
                ('reste', models.IntegerField(null=True, verbose_name='reste')),
                ('fini', models.BinaryField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64, verbose_name='nom et prenom')),
                ('adresse', models.CharField(max_length=64)),
                ('tel', models.CharField(max_length=24, verbose_name='numero de télephone')),
            ],
            options={
                'unique_together': {('adresse', 'tel')},
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('unite_entrant', models.CharField(max_length=64)),
                ('unite_sortant', models.CharField(max_length=64)),
                ('rapport', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant.Fournisseur')),
            ],
            options={
                'unique_together': {('nom', 'fournisseur', 'prix')},
            },
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('temp', models.IntegerField(verbose_name='temp de cuisson(en minutes)')),
                ('prix', models.IntegerField()),
                ('ingredient', models.ManyToManyField(to='Restaurant.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('recette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant.Recette')),
            ],
            options={
                'verbose_name_plural': 'Repas',
                'unique_together': {('recette', 'quantite')},
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commandee', models.BooleanField(default=False)),
                ('servi', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant.Client')),
                ('repas', models.ManyToManyField(to='Restaurant.Repas')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme', models.IntegerField(verbose_name='somme payée')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant.Commande')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Panier'),
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant.Fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Produit')),
            ],
            options={
                'unique_together': {('produit', 'quantite')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('produit', 'quantite')},
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant.Client')),
                ('recette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant.Recette')),
            ],
            options={
                'unique_together': {('client', 'recette')},
            },
        ),
    ]
